apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: magtape
    magtape: hpa
  name: magtape
  namespace: magtape-system
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: magtape
  targetCPUUtilizationPercentage: 80