apiVersion: v1
kind: Pod
metadata:
  labels:
    run: toolbox
  name: test-pod02
spec:
  containers:
  - command:
    - sleep
    - "360000"
    image: jmsearcy/twrtools
    imagePullPolicy: Always
    name: toolbox
  volumes:
  - name: default-token
    hostPath:
      path: /data
