apiVersion: v1
kind: Pod
metadata:
  labels:
    run: toolbox
  name: test-pod05
spec:
  containers:
  - command:
    - sleep
    - "360000"
    image: jmsearcy/twrtools
    imagePullPolicy: Always
    name: toolbox
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
    resources:
      limits:
        cpu: "50m"
        memory: "128Mi"
      requests:
        cpu: "50m"
        memory: "128Mi"
  volumes:
  - name: default-token
    emptyDir:
      sizeLimit: "50M"
