apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-svc
  name: test-svc01
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: test-svc
  type: ClusterIP
