apiVersion: apps/v1
kind: Deployment
metadata:
  name: magtape
  namespace: magtape-system
  labels:
    app: magtape
spec:
  # Set Replicas to 1
  replicas: 1
  template:
    spec:
      containers:
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:0.10
        args:
          - "--policies=magtape-system"
          - "--require-policy-label=true"
          # Add Resources to Cache
          - "--replicate=apps/v1/deployments"
          - "--replicate=v1/services"
          - "--replicate-cluster=v1/namespaces"
