name: rego-checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# Jobs
jobs:
  # Job to lint code
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opa-version:
          - 0.19.2

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.opa-version }}
      uses: actions/setup-python@v1
      with:
        opa-version: ${{ matrix.opa-version }}

    - name: Install Dependencies
      timeout-minutes: 5
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/${{ matrix.opa-version }}/opa_linux_amd64
        mv opa /usr/local/bin

    - name: Lint
      timeout-minutes: 5
      run: |
        make ci-lint-rego
  
  # Job to execute unit tests
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opa-version:
          - 0.19.2

    steps:
    - uses: actions/checkout@v2

    - name: Execute Unit Tests
      timeout-minutes: 5
      run: |
        make test-rego